# Generated by Django 5.1.2 on 2025-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, db_column='file', null=True, upload_to='expense_files/'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
