# Generated by Django 5.1.2 on 2025-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxuser',
            name='job',
        ),
    ]
