# Generated by Django 5.1.2 on 2025-05-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_file_file_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='incomeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.income'),
        ),
        migrations.AlterField(
            model_name='file',
            name='expenseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expense'),
        ),
    ]
