# Generated by Django 5.1.2 on 2025-05-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('is_deductible', models.BooleanField(db_column='isDeductible', default=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='fileid', primary_key=True, serialize=False)),
                ('filepath', models.CharField(db_column='filepath', max_length=255)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year')),
                ('category', models.CharField(db_column='category', max_length=30)),
                ('charge_income', models.DecimalField(db_column='chargeIncome', decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(db_column='taxRate', decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(db_column='tax_amount', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('phone', models.CharField(db_column='phone', max_length=15, null=True)),
                ('job', models.CharField(db_column='job', max_length=30, null=True)),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('marital_status', models.BooleanField(db_column='marital_status', default=False)),
                ('ethnicity', models.CharField(db_column='ethnicity', max_length=30, null=True)),
                ('nationality', models.CharField(db_column='nationality', max_length=30, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='TaxUser',
            fields=[
                ('taxuserid', models.AutoField(db_column='taxuserid', primary_key=True, serialize=False)),
                ('tax_year', models.IntegerField(db_column='tax_year')),
                ('tax_income', models.DecimalField(db_column='tax_income', decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('job', models.CharField(db_column='job', max_length=30, null=True)),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'tax_user',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationshipid', models.AutoField(db_column='relationshipid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('birth_date', models.DateField(db_column='birth_date', null=True)),
                ('relationship_type', models.CharField(db_column='relationship_type', max_length=50)),
                ('job', models.CharField(db_column='job', max_length=30, null=True)),
                ('expenses', models.DecimalField(db_column='expenses', decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='notificationid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=150)),
                ('content', models.TextField(db_column='content')),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('incomeid', models.AutoField(db_column='incomeid', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('income_type', models.CharField(db_column='income_type', max_length=50)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('job', models.CharField(blank=True, db_column='job', max_length=30, null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=50, null=True)),
                ('category', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseid', models.AutoField(db_column='expenseid', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='datetime')),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('type', models.CharField(db_column='type', max_length=30)),
                ('category', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('file', models.ForeignKey(db_column='fileid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.file')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
